[project]
authors = ["Sara <sara.fer.malv@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "scVAG"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[environments]
scvag-cuda = ["scVAG_cuda"]
